name: mir-kiosk-desktop-example
version: '0.1'
summary: example (kodi) desktop kiosk
description: |
  example (kodi) desktop kiosk
base: core20
confinement: strict
grade: devel

apps:
  mir-kiosk-desktop-example:
    command-chain:
      - env-setup
    command: usr/local/bin/x11_kiosk_launch $SNAP/usr/bin/kodi

architectures:
  - build-on: amd64

parts:
  ppa-setup:
    plugin: nil
    # Use the upstream team-xbmc PPA
    override-pull: |
      sudo apt --assume-yes install software-properties-common
      sudo add-apt-repository -yu ppa:team-xbmc/ppa
      snapcraftctl pull

  kodi:
    after: [ ppa-setup ]
    plugin: nil
    override-pull: |
      snapcraftctl pull
      kodi_version=`LANG=C apt-cache policy kodi-wayland | sed -rne 's/^\s+Candidate:\s+([^-]*)-.+$/\1/p'`
      snapcraftctl set-version $kodi_version
    stage-packages:
      - kodi
      - kodi-wayland
      - kodi-visualization-spectrum
      - kodi-repository-kodi
      - kodi-inputstream-adaptive
      - python
      - samba-libs
      - samba-common-bin
      - samba-common
      - libfstrcmp0
      - libpulse0
      - libaudio2
      - libsndio7.0
      - va-driver-all

  mir-kiosk-desktop:
    plugin: nil
    stage-snaps: [mir-kiosk-desktop]
    override-build: |
      snapcraftctl build
      sed s/\$\{SNAPCRAFT_PROJECT_NAME}/${SNAPCRAFT_PROJECT_NAME}/g --in-place $SNAPCRAFT_PART_INSTALL/desktop/setup
      sed s/\$\{SNAPCRAFT_PROJECT_NAME}/${SNAPCRAFT_PROJECT_NAME}/g --in-place $SNAPCRAFT_PART_INSTALL/desktop/mir-kiosk-desktop.desktop

  connect-interfaces:
    plugin: dump
    source: connect-interfaces
    override-build: |
      snapcraftctl build
      MY_PROJECT_INTERFACES="hardware-observe login-session-control mount-observe network-observe system-observe wayland"
      sed s/\$\{MY_PROJECT_INTERFACES}/"${MY_PROJECT_INTERFACES}"/g --in-place $SNAPCRAFT_PART_INSTALL/connect-interfaces
      sed s/\$\{SNAPCRAFT_PROJECT_NAME}/${SNAPCRAFT_PROJECT_NAME}/g --in-place $SNAPCRAFT_PART_INSTALL/connect-interfaces

layout:
  /usr/share/X11:
    bind: $SNAP/usr/share/X11
  /usr/bin/xkbcomp:
    symlink: $SNAP/usr/bin/xkbcomp
  /usr/share/icons:
    bind: $SNAP/usr/share/icons
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /etc/fonts:
    bind: $SNAP/etc/fonts
  /etc/glvnd:
    bind: $SNAP/etc/glvnd
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri:
    bind: $SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/kodi:
    bind: $SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/kodi
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/pulseaudio:
    bind: $SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/pulseaudio
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/samba:
    bind: $SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/samba
  /usr/share/glvnd:
    bind: $SNAP/usr/share/glvnd
  /usr/share/kodi:
    bind: $SNAP/usr/share/kodi
  /usr/share/samba:
    bind: $SNAP/usr/share/samba

environment:
  SHELL: bash
  LC_ALL: C.UTF-8
  LD_LIBRARY_PATH: ${LD_LIBRARY_PATH}:${SNAP}/usr/lib/:/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/pulseaudio:/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/samba
  PATH: $SNAP/bin/:$SNAP/usr/bin/:${PATH}
  # XDG config
  XDG_CACHE_HOME:  $SNAP_USER_COMMON/.cache
  XDG_CONFIG_HOME: $SNAP_USER_DATA/.config
  # Prep Kodi
  WINDOWING: wayland
  PULSE_SERVER: unix:$XDG_RUNTIME_DIR/../pulse/native

plugs:
  opengl:         # For Mir
  wayland:        # For Mir
  network-bind:   # For Mir (to serve X11)
  login-session-control: # To start a desktop session
  hardware-observe: # To start a desktop session
  # For Kodi...
  audio-playback:
  avahi-observe:
  locale-control:
  mount-observe:
  network-observe:
  removable-media:
  shutdown:
  system-observe:
